service: aws-nodejs
package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - "**"
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  environment:
    ACCOUNT_ID: ${file(./env/dev.json):ACCOUNT_ID}
    API_ENDPOINT: ${file(./env/dev.json):API_ENDPOINT}
    APP_ID: ${file(./env/dev.json):APP_ID}
functions:
  playerIndexer:
    handler: handlers/playerIndexer/handler.personalDataIndexer
    package:
      include: 
        - handlers/playerIndexer/**
        - services/**
        - node_modules/**
    events:
      - schedule:
          name: accountIndexer
          rate: cron(0 12 * * ? *)
  playerInfo:
    handler: handlers/playerInfo/handler.playerInfo
    package:
      include: 
        -handlers/ playerInfo/**
        - services/**
        - node_modules/**
    events:
      - http:
          path: player-info
          method: get
          cors: true