service: aws-nodejs
provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  environment:
    ACCOUNT_ID: ${file(./env/dev.json):ACCOUNT_ID}
    API_ENDPOINT: ${file(./env/dev.json):API_ENDPOINT}
    APP_ID: ${file(./env/dev.json):APP_ID}
    S3_BUCKET: ${file(./env/dev.json):S3_BUCKET}
functions:
  playerIndexer:
    handler: playerIndexer/handler.personalDataIndexer
    events:
      - schedule:
        name: accountIndexer
        rate: cron(0 12 * * ? *)
  playerAchievementsIndexer:
    handler: playerIndexer/handler.achievementIndexer
  vehicleIndexer:
    handler: vehicleIndexer/handler.indexer