service: aws-nodejs
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  environment:
    ACCOUNT_ID: ${file(./env/dev.json):ACCOUNT_ID}
    API_ENDPOINT: ${file(./env/dev.json):API_ENDPOINT}
    APP_ID: ${file(./env/dev.json):APP_ID}
functions:
  playerIndexer:
    handler: playerIndexer/handler.personalDataIndexer
    events:
      - schedule:
          name: accountIndexer
          rate: cron(0 12 * * ? *)
  playerInfo:
    handler: playerInfo/handler.playerInfo
    events:
      - http:
          path: player-info
          method: get
          cors: true