service: aws-nodejs

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - "**"

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  environment:
    NODE_ENV: production
    API_ENDPOINT: https://api.wotblitz.com/wotb
    APP_ID: ${env:APP_ID}
    ACCOUNT_ID: ${env:ACCOUNT_ID}

functions:
  playerIndexer:
    handler: src/handlers/playerIndexer/handler.personalDataIndexer
    package:
      include: 
        - src/handlers/playerIndexer/**
        - src/services/**
        - src/utils/**
        - node_modules/**
    events:
      - schedule:
          name: accountIndexer
          rate: cron(0 6 * * ? *)
  playerVehicleIndexer:
    handler: src/handlers/playerVehicleIndexer/handler.playerVehicleIndexer
    package:
      include: 
        - src/handlers/playerVehicleIndexer/**
        - src/services/**
        - src/utils/**
        - node_modules/**
    events:
      - schedule:
          name: playerVehicleIndexer
          rate: cron(0 6 * * ? *)
  vehicleIndexer:
    handler: src/handlers/vehicleIndexer/handler.vehicleIndexer
    package:
      include: 
        - src/handlers/vehicleIndexer/**
        - src/services/**
        - src/utils/**
        - node_modules/**
  playerInfo:
    handler: src/handlers/playerInfo/handler.playerInfo
    package:
      include: 
        - src/handlers/playerInfo/**
        - src/services/**
        - src/utils/**
        - node_modules/**
    events:
      - http:
          path: player-info
          method: get
          cors: true
  playerVehicles:
    handler: src/handlers/playerVehicles/handler.vehicleList
    package:
      include: 
        - src/handlers/playerVehicles/**
        - src/services/**
        - src/utils/**
        - node_modules/**
    events:
      - http:
          path: player-vehicles
          method: get
          cors: true
  playerVehicleInfo:
    handler: src/handlers/playerVehicles/handler.vehicleInfo
    package:
      include: 
        - src/handlers/playerVehicles/**
        - src/services/**
        - src/utils/**
        - node_modules/**
    events:
      - http:
          path: player-vehicle
          method: get
          cors: true