# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          keys: v1-test-job-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-test-job-{{ checksum "package.json" }}
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - restore_cache:
          keys: v1-build-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run deploy
      - save_cache:
          paths:
            - node_modules
          key: v1-build-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master